# ===================================================================
# application-prod.yml - CORRECTED for PostgreSQL Production
# ===================================================================

spring:
  config:
    activate:
      on-profile: prod

  # ==========================================
  # DATABASE CONFIGURATION (PROD) - FIXED FOR POSTGRESQL
  # ==========================================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tvboot_prod}?ApplicationName=tvboot-prod&stringtype=unspecified&sslmode=require
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}
    hikari:
      pool-name: TivioHikariPoolProd
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 0
      register-mbeans: true
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

  # ==========================================
  # JPA & HIBERNATE CONFIGURATION (PROD) - FIXED
  # ==========================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false

  # ==========================================
  # FLYWAY CONFIGURATION (PROD)
  # ==========================================
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    encoding: UTF-8
    connect-retries: 5

# ==========================================
# SERVER CONFIGURATION (PROD)
# ==========================================
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# ==========================================
# LOGGING CONFIGURATION (PROD)
# ==========================================
logging:
  level:
    root: INFO
    com.tvboot.tivio: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
  file:
    path: logs
    name: logs/tvboot-prod.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
      max-history: 14
      total-size-cap: 2GB

# ==========================================
# ACTUATOR CONFIGURATION (PROD)
# ==========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  security:
    enabled: true

# ==========================================
# APP CUSTOM CONFIGURATION (PROD)
# ==========================================
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000
  upload:
    logos:
      path: uploads/logos/channels/
      max-size: 5242880
  cdn:
    enabled: true
    base-url: ${CDN_URL:https://cdn.myhotel.tv}
    logos-path: /logos/channels

# ==========================================
# SWAGGER/OPENAPI CONFIGURATION (PROD)
# ==========================================
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false