CREATE TABLE epg_entries
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    start_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    genre       VARCHAR(255),
    channel_id  BIGINT       NOT NULL,
    CONSTRAINT pk_epg_entries PRIMARY KEY (id)
);

CREATE TABLE guests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pms_guest_id    VARCHAR(255) NOT NULL,
    title      VARCHAR(50) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(255),
    nationality     VARCHAR(255),
    language_id     BIGINT,
    date_of_birth   date,
    gender          VARCHAR(255),
    vip_status      BOOLEAN,
    loyalty_level   VARCHAR(255),
    current_room_id BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_guests PRIMARY KEY (id)
);

CREATE TABLE languages
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(100) NOT NULL,
    native_name         VARCHAR(100) NOT NULL,
    iso_639_1           VARCHAR(2)   NOT NULL,
    iso_639_2           VARCHAR(3),
    locale_code         VARCHAR(5),
    charset             VARCHAR(50),
    flag_path           VARCHAR(255),
    is_rtl              BOOLEAN      NOT NULL,
    is_admin_enabled    BOOLEAN      NOT NULL,
    is_guest_enabled    BOOLEAN      NOT NULL,
    display_order       INTEGER      NOT NULL,
    font_family         VARCHAR(100),
    currency_code       VARCHAR(20),
    currency_symbol     VARCHAR(10),
    date_format         VARCHAR(50),
    time_format         VARCHAR(50),
    number_format       VARCHAR(50),
    decimal_separator   CHAR,
    thousands_separator CHAR,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_number     VARCHAR(255) NOT NULL,
    room_type       VARCHAR(255) NOT NULL,
    floor_number    INTEGER,
    occupied        BOOLEAN DEFAULT FALSE,
    description     TEXT,
    -- Embedded RoomGuest fields (cleaner column names)
    guest_pms_id VARCHAR(255),
    guest_title VARCHAR(50),
    guest_language VARCHAR(10),
    guest_type VARCHAR(50),
    guest_first_name VARCHAR(100),
    guest_last_name VARCHAR(100),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE terminals
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    terminal_code    VARCHAR(50)  NOT NULL,
    ip_address       VARCHAR(15)  NOT NULL,
    mac_address      VARCHAR(17)  NOT NULL,
    device_type      VARCHAR(20)  ,
    location_type      VARCHAR(20)  ,
    location_identifier  VARCHAR(20)  ,
    room_id              BIGINT,
    brand            VARCHAR(50)  ,
    model            VARCHAR(50)  ,
    platform         VARCHAR(20),
    firmware_version VARCHAR(20),
    app_version  VARCHAR(20),
    last_seen        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    uptime           DOUBLE PRECISION,
    is_online        BOOLEAN      ,
    is_active        BOOLEAN      ,
    soft_ap          BOOLEAN    default true ,
    comment            VARCHAR(250)  ,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_terminals PRIMARY KEY (id),
    CONSTRAINT fk_terminals_room FOREIGN KEY (room_id)
        REFERENCES rooms (id)
        ON DELETE SET NULL
);

CREATE TABLE translations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    language_id   BIGINT       NOT NULL,
    message_key   VARCHAR(255) NOT NULL,
    message_value TEXT         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_translations PRIMARY KEY (id)
);

CREATE TABLE tv_channel_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tv_channel_categories PRIMARY KEY (id)
);


CREATE TABLE tv_channels
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_number INTEGER UNIQUE,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(255),
    ip             VARCHAR(255) UNIQUE  NOT NULL,
    port           INTEGER  NOT NULL,
    web_url     VARCHAR(255),
    category_id    BIGINT,
    language_id    BIGINT,
    logo_path      VARCHAR(255),
    is_active      BOOLEAN      NOT NULL,
    is_available   BOOLEAN,
    sort_order     INTEGER UNIQUE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tv_channels PRIMARY KEY (id),
    CONSTRAINT uk_tv_channels_channel_number UNIQUE (channel_number),
    CONSTRAINT uk_tv_channels_ip UNIQUE (ip),
    CONSTRAINT uk_tv_channels_sort_order UNIQUE (sort_order)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    role       VARCHAR(50),
    is_active  BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE weblinks
(
    id         SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(200) NOT NULL,
    url        VARCHAR(500) NOT NULL,
    svg_icon   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_weblinks PRIMARY KEY (id)
);
-- Create amenities table for Hotel New Day IPTV System

CREATE TABLE amenities (
                           id BIGSERIAL PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           short_description VARCHAR(200),
                           html_content TEXT,
                           image_url VARCHAR(500),
                           thumbnail_url VARCHAR(500),
                           available BOOLEAN NOT NULL DEFAULT true,
                           category VARCHAR(50) NOT NULL,
                           location VARCHAR(255),
                           contact_phone VARCHAR(50),
                           contact_extension VARCHAR(20),
                           opening_time TIME,
                           closing_time TIME,
                           display_order INTEGER DEFAULT 0,
                           show_in_menu BOOLEAN DEFAULT true,
                           css_style TEXT
);
CREATE TABLE access_points (
    -- Primary Key
                               id BIGSERIAL PRIMARY KEY,

    -- Data Fields
                               ssid VARCHAR(32),
                               password VARCHAR(63),

    -- Boolean Flags (using BOOLEAN type, maps well to Java Boolean)
                               is_available BOOLEAN NOT NULL DEFAULT FALSE,
                               is_enabled BOOLEAN NOT NULL DEFAULT FALSE,

    -- Enum Fields (mapped to VARCHAR for String-based enumeration)
                               security_protocol VARCHAR(20), -- Maps to WifiSecurityProtocol enum (e.g., 'WPA2_PSK', 'OPEN')
                               type VARCHAR(20) NOT NULL,      -- Maps to AccessPointType enum (e.g., 'INTEGRATED', 'EXTERNAL')

    -- Timestamps (using TIMESTAMP WITHOUT TIME ZONE for LocalDateTime)
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP WITHOUT TIME ZONE,

    -- Relationship (Foreign Key for the One-to-One relationship with Terminal)
                               terminal_id BIGINT NOT NULL UNIQUE,

    -- Constraints
                               CONSTRAINT fk_terminal
                                   FOREIGN KEY (terminal_id)
                                       REFERENCES terminals (id) -- Assuming your Terminal table is named 'terminal'
);

ALTER TABLE guests
    ADD CONSTRAINT uc_guests_pms_guest UNIQUE (pms_guest_id);

ALTER TABLE languages
    ADD CONSTRAINT uc_languages_iso_639_1 UNIQUE (iso_639_1);

ALTER TABLE rooms
    ADD CONSTRAINT uc_rooms_room_number UNIQUE (room_number);

ALTER TABLE terminals
    ADD CONSTRAINT uc_terminals_mac_address UNIQUE (mac_address);

ALTER TABLE terminals
    ADD CONSTRAINT uc_terminals_terminal_code UNIQUE (terminal_code);

ALTER TABLE tv_channel_categories
    ADD CONSTRAINT uc_tv_channel_categories_name UNIQUE (name);


ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE translations
    ADD CONSTRAINT uq_translation_language_key UNIQUE (language_id, message_key);

CREATE INDEX idx_room_floor ON rooms (floor_number);

CREATE INDEX idx_room_number ON rooms (room_number);

CREATE INDEX idx_room_type ON rooms (room_type);

CREATE INDEX idx_translation_message_key ON translations (message_key);

ALTER TABLE epg_entries
    ADD CONSTRAINT FK_EPG_ENTRIES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES tv_channels (id);

ALTER TABLE guests
    ADD CONSTRAINT FK_GUESTS_ON_CURRENT_ROOM FOREIGN KEY (current_room_id) REFERENCES rooms (id);

ALTER TABLE guests
    ADD CONSTRAINT FK_GUESTS_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES languages (id);

ALTER TABLE translations
    ADD CONSTRAINT FK_TRANSLATION_LANGUAGE FOREIGN KEY (language_id) REFERENCES languages (id);

CREATE INDEX idx_translation_language_id ON translations (language_id);

ALTER TABLE tv_channels
    ADD CONSTRAINT FK_TV_CHANNELS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES tv_channel_categories (id);

ALTER TABLE tv_channels
    ADD CONSTRAINT FK_TV_CHANNELS_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES languages (id);